// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWolf1yqS5RPnOZVPWynFGGhX70fTnB7U',
    appId: '1:802338516078:web:921dfbadc9cd3cd0e9ca7f',
    messagingSenderId: '802338516078',
    projectId: 'fixxa-83fe2',
    authDomain: 'fixxa-83fe2.firebaseapp.com',
    storageBucket: 'fixxa-83fe2.firebasestorage.app',
    measurementId: 'G-L0S8QWWESJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASaRwzT-Z6XtgC8UCpCthIXBPtWG-TGiQ',
    appId: '1:802338516078:android:7e75528d4ce5be5ee9ca7f',
    messagingSenderId: '802338516078',
    projectId: 'fixxa-83fe2',
    storageBucket: 'fixxa-83fe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1WCDxbC8cLe8DPmi0MpVnq-5VxhTFt2U',
    appId: '1:802338516078:ios:597f6119fcd862f4e9ca7f',
    messagingSenderId: '802338516078',
    projectId: 'fixxa-83fe2',
    storageBucket: 'fixxa-83fe2.firebasestorage.app',
    iosBundleId: 'com.example.fixxaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1WCDxbC8cLe8DPmi0MpVnq-5VxhTFt2U',
    appId: '1:802338516078:ios:597f6119fcd862f4e9ca7f',
    messagingSenderId: '802338516078',
    projectId: 'fixxa-83fe2',
    storageBucket: 'fixxa-83fe2.firebasestorage.app',
    iosBundleId: 'com.example.fixxaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWolf1yqS5RPnOZVPWynFGGhX70fTnB7U',
    appId: '1:802338516078:web:d2ad0fe3440d9055e9ca7f',
    messagingSenderId: '802338516078',
    projectId: 'fixxa-83fe2',
    authDomain: 'fixxa-83fe2.firebaseapp.com',
    storageBucket: 'fixxa-83fe2.firebasestorage.app',
    measurementId: 'G-7SZBRZ86PZ',
  );
}
